const PendleYieldTokenAbi = [
    {
        inputs: [
            { internalType: 'address', name: '_SY', type: 'address' },
            { internalType: 'address', name: '_PT', type: 'address' },
            { internalType: 'string', name: '_name', type: 'string' },
            { internalType: 'string', name: '_symbol', type: 'string' },
            { internalType: 'uint8', name: '__decimals', type: 'uint8' },
            { internalType: 'uint256', name: '_expiry', type: 'uint256' },
            { internalType: 'bool', name: '_doCacheIndexSameBlock', type: 'bool' },
        ],
        stateMutability: 'nonpayable',
        type: 'constructor',
    },
    { inputs: [], name: 'ArrayEmpty', type: 'error' },
    { inputs: [], name: 'ArrayLengthMismatch', type: 'error' },
    { inputs: [], name: 'InvalidShortString', type: 'error' },
    {
        inputs: [{ internalType: 'string', name: 'str', type: 'string' }],
        name: 'StringTooLong',
        type: 'error',
    },
    { inputs: [], name: 'YCExpired', type: 'error' },
    { inputs: [], name: 'YCNoFloatingSy', type: 'error' },
    { inputs: [], name: 'YCNotExpired', type: 'error' },
    { inputs: [], name: 'YCNothingToRedeem', type: 'error' },
    { inputs: [], name: 'YCPostExpiryDataNotSet', type: 'error' },
    {
        inputs: [
            { internalType: 'uint256', name: 'actualSy', type: 'uint256' },
            { internalType: 'uint256', name: 'requiredSy', type: 'uint256' },
        ],
        name: 'YieldContractInsufficientSy',
        type: 'error',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'owner',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'spender',
                type: 'address',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'value',
                type: 'uint256',
            },
        ],
        name: 'Approval',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'caller',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'receiver',
                type: 'address',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'amountPYToRedeem',
                type: 'uint256',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'amountSyOut',
                type: 'uint256',
            },
        ],
        name: 'Burn',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: 'uint256',
                name: 'amountInterestFee',
                type: 'uint256',
            },
        ],
        name: 'CollectInterestFee',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'rewardToken',
                type: 'address',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'amountRewardFee',
                type: 'uint256',
            },
        ],
        name: 'CollectRewardFee',
        type: 'event',
    },
    { anonymous: false, inputs: [], name: 'EIP712DomainChanged', type: 'event' },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'caller',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'receiverPT',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'receiverYT',
                type: 'address',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'amountSyToMint',
                type: 'uint256',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'amountPYOut',
                type: 'uint256',
            },
        ],
        name: 'Mint',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'uint256',
                name: 'newIndex',
                type: 'uint256',
            },
        ],
        name: 'NewInterestIndex',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'user', type: 'address' },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'interestOut',
                type: 'uint256',
            },
        ],
        name: 'RedeemInterest',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'user', type: 'address' },
            {
                indexed: false,
                internalType: 'uint256[]',
                name: 'amountRewardsOut',
                type: 'uint256[]',
            },
        ],
        name: 'RedeemRewards',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'from', type: 'address' },
            { indexed: true, internalType: 'address', name: 'to', type: 'address' },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'value',
                type: 'uint256',
            },
        ],
        name: 'Transfer',
        type: 'event',
    },
    {
        inputs: [],
        name: 'DOMAIN_SEPARATOR',
        outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'PT',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'SY',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'owner', type: 'address' },
            { internalType: 'address', name: 'spender', type: 'address' },
        ],
        name: 'allowance',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'spender', type: 'address' },
            { internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'approve',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
        name: 'balanceOf',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'decimals',
        outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'doCacheIndexSameBlock',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'eip712Domain',
        outputs: [
            { internalType: 'bytes1', name: 'fields', type: 'bytes1' },
            { internalType: 'string', name: 'name', type: 'string' },
            { internalType: 'string', name: 'version', type: 'string' },
            { internalType: 'uint256', name: 'chainId', type: 'uint256' },
            { internalType: 'address', name: 'verifyingContract', type: 'address' },
            { internalType: 'bytes32', name: 'salt', type: 'bytes32' },
            { internalType: 'uint256[]', name: 'extensions', type: 'uint256[]' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'expiry',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'factory',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getPostExpiryData',
        outputs: [
            { internalType: 'uint256', name: 'firstPYIndex', type: 'uint256' },
            {
                internalType: 'uint256',
                name: 'totalSyInterestForTreasury',
                type: 'uint256',
            },
            {
                internalType: 'uint256[]',
                name: 'firstRewardIndexes',
                type: 'uint256[]',
            },
            { internalType: 'uint256[]', name: 'userRewardOwed', type: 'uint256[]' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getRewardTokens',
        outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'isExpired',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'receiverPT', type: 'address' },
            { internalType: 'address', name: 'receiverYT', type: 'address' },
        ],
        name: 'mintPY',
        outputs: [
            { internalType: 'uint256', name: 'amountPYOut', type: 'uint256' },
        ],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address[]', name: 'receiverPTs', type: 'address[]' },
            { internalType: 'address[]', name: 'receiverYTs', type: 'address[]' },
            { internalType: 'uint256[]', name: 'amountSyToMints', type: 'uint256[]' },
        ],
        name: 'mintPYMulti',
        outputs: [
            { internalType: 'uint256[]', name: 'amountPYOuts', type: 'uint256[]' },
        ],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'name',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
        name: 'nonces',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'owner', type: 'address' },
            { internalType: 'address', name: 'spender', type: 'address' },
            { internalType: 'uint256', name: 'value', type: 'uint256' },
            { internalType: 'uint256', name: 'deadline', type: 'uint256' },
            { internalType: 'uint8', name: 'v', type: 'uint8' },
            { internalType: 'bytes32', name: 'r', type: 'bytes32' },
            { internalType: 'bytes32', name: 's', type: 'bytes32' },
        ],
        name: 'permit',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'postExpiry',
        outputs: [
            { internalType: 'uint128', name: 'firstPYIndex', type: 'uint128' },
            {
                internalType: 'uint128',
                name: 'totalSyInterestForTreasury',
                type: 'uint128',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'pyIndexCurrent',
        outputs: [
            { internalType: 'uint256', name: 'currentIndex', type: 'uint256' },
        ],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'pyIndexLastUpdatedBlock',
        outputs: [{ internalType: 'uint128', name: '', type: 'uint128' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'pyIndexStored',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'user', type: 'address' },
            { internalType: 'bool', name: 'redeemInterest', type: 'bool' },
            { internalType: 'bool', name: 'redeemRewards', type: 'bool' },
        ],
        name: 'redeemDueInterestAndRewards',
        outputs: [
            { internalType: 'uint256', name: 'interestOut', type: 'uint256' },
            { internalType: 'uint256[]', name: 'rewardsOut', type: 'uint256[]' },
        ],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'redeemInterestAndRewardsPostExpiryForTreasury',
        outputs: [
            { internalType: 'uint256', name: 'interestOut', type: 'uint256' },
            { internalType: 'uint256[]', name: 'rewardsOut', type: 'uint256[]' },
        ],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'receiver', type: 'address' }],
        name: 'redeemPY',
        outputs: [
            { internalType: 'uint256', name: 'amountSyOut', type: 'uint256' },
        ],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address[]', name: 'receivers', type: 'address[]' },
            {
                internalType: 'uint256[]',
                name: 'amountPYToRedeems',
                type: 'uint256[]',
            },
        ],
        name: 'redeemPYMulti',
        outputs: [
            { internalType: 'uint256[]', name: 'amountSyOuts', type: 'uint256[]' },
        ],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'rewardIndexesCurrent',
        outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'setPostExpiryData',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'syReserve',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'symbol',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'totalSupply',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'to', type: 'address' },
            { internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'transfer',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'from', type: 'address' },
            { internalType: 'address', name: 'to', type: 'address' },
            { internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'transferFrom',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '', type: 'address' }],
        name: 'userInterest',
        outputs: [
            { internalType: 'uint128', name: 'index', type: 'uint128' },
            { internalType: 'uint128', name: 'accrued', type: 'uint128' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: '', type: 'address' },
            { internalType: 'address', name: '', type: 'address' },
        ],
        name: 'userReward',
        outputs: [
            { internalType: 'uint128', name: 'index', type: 'uint128' },
            { internalType: 'uint128', name: 'accrued', type: 'uint128' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
];

export const ActionMiscV3Abi = [
    {
        inputs: [
            { internalType: 'uint256', name: 'actualPYOut', type: 'uint256' },
            { internalType: 'uint256', name: 'requiredPYOut', type: 'uint256' },
        ],
        name: 'RouterInsufficientPYOut',
        type: 'error',
    },
    {
        inputs: [
            { internalType: 'uint256', name: 'actualSyOut', type: 'uint256' },
            { internalType: 'uint256', name: 'requiredSyOut', type: 'uint256' },
        ],
        name: 'RouterInsufficientSyOut',
        type: 'error',
    },
    {
        inputs: [
            { internalType: 'uint256', name: 'actualTokenOut', type: 'uint256' },
            { internalType: 'uint256', name: 'requiredTokenOut', type: 'uint256' },
        ],
        name: 'RouterInsufficientTokenOut',
        type: 'error',
    },
    {
        inputs: [
            { internalType: 'bool', name: 'success', type: 'bool' },
            { internalType: 'bytes', name: 'res', type: 'bytes' },
        ],
        name: 'SimulationResults',
        type: 'error',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'caller',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'receiver',
                type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'YT', type: 'address' },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netSyIn',
                type: 'uint256',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netPyOut',
                type: 'uint256',
            },
        ],
        name: 'MintPyFromSy',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'caller',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'tokenIn',
                type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'YT', type: 'address' },
            {
                indexed: false,
                internalType: 'address',
                name: 'receiver',
                type: 'address',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netTokenIn',
                type: 'uint256',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netPyOut',
                type: 'uint256',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netSyInterm',
                type: 'uint256',
            },
        ],
        name: 'MintPyFromToken',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'caller',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'tokenIn',
                type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'SY', type: 'address' },
            {
                indexed: false,
                internalType: 'address',
                name: 'receiver',
                type: 'address',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netTokenIn',
                type: 'uint256',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netSyOut',
                type: 'uint256',
            },
        ],
        name: 'MintSyFromToken',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'caller',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'receiver',
                type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'YT', type: 'address' },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netPyIn',
                type: 'uint256',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netSyOut',
                type: 'uint256',
            },
        ],
        name: 'RedeemPyToSy',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'caller',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'tokenOut',
                type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'YT', type: 'address' },
            {
                indexed: false,
                internalType: 'address',
                name: 'receiver',
                type: 'address',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netPyIn',
                type: 'uint256',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netTokenOut',
                type: 'uint256',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netSyInterm',
                type: 'uint256',
            },
        ],
        name: 'RedeemPyToToken',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'caller',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'tokenOut',
                type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'SY', type: 'address' },
            {
                indexed: false,
                internalType: 'address',
                name: 'receiver',
                type: 'address',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netSyIn',
                type: 'uint256',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'netTokenOut',
                type: 'uint256',
            },
        ],
        name: 'RedeemSyToToken',
        type: 'event',
    },
    {
        inputs: [{ internalType: 'address[]', name: 'markets', type: 'address[]' }],
        name: 'boostMarkets',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'receiver', type: 'address' },
            { internalType: 'address', name: 'YT', type: 'address' },
            { internalType: 'uint256', name: 'netSyIn', type: 'uint256' },
            { internalType: 'uint256', name: 'minPyOut', type: 'uint256' },
        ],
        name: 'mintPyFromSy',
        outputs: [{ internalType: 'uint256', name: 'netPyOut', type: 'uint256' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'receiver', type: 'address' },
            { internalType: 'address', name: 'YT', type: 'address' },
            { internalType: 'uint256', name: 'minPyOut', type: 'uint256' },
            {
                components: [
                    { internalType: 'address', name: 'tokenIn', type: 'address' },
                    { internalType: 'uint256', name: 'netTokenIn', type: 'uint256' },
                    { internalType: 'address', name: 'tokenMintSy', type: 'address' },
                    { internalType: 'address', name: 'pendleSwap', type: 'address' },
                    {
                        components: [
                            {
                                internalType: 'enum SwapType',
                                name: 'swapType',
                                type: 'uint8',
                            },
                            { internalType: 'address', name: 'extRouter', type: 'address' },
                            { internalType: 'bytes', name: 'extCalldata', type: 'bytes' },
                            { internalType: 'bool', name: 'needScale', type: 'bool' },
                        ],
                        internalType: 'struct SwapData',
                        name: 'swapData',
                        type: 'tuple',
                    },
                ],
                internalType: 'struct TokenInput',
                name: 'input',
                type: 'tuple',
            },
        ],
        name: 'mintPyFromToken',
        outputs: [
            { internalType: 'uint256', name: 'netPyOut', type: 'uint256' },
            { internalType: 'uint256', name: 'netSyInterm', type: 'uint256' },
        ],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'receiver', type: 'address' },
            { internalType: 'address', name: 'SY', type: 'address' },
            { internalType: 'uint256', name: 'minSyOut', type: 'uint256' },
            {
                components: [
                    { internalType: 'address', name: 'tokenIn', type: 'address' },
                    { internalType: 'uint256', name: 'netTokenIn', type: 'uint256' },
                    { internalType: 'address', name: 'tokenMintSy', type: 'address' },
                    { internalType: 'address', name: 'pendleSwap', type: 'address' },
                    {
                        components: [
                            {
                                internalType: 'enum SwapType',
                                name: 'swapType',
                                type: 'uint8',
                            },
                            { internalType: 'address', name: 'extRouter', type: 'address' },
                            { internalType: 'bytes', name: 'extCalldata', type: 'bytes' },
                            { internalType: 'bool', name: 'needScale', type: 'bool' },
                        ],
                        internalType: 'struct SwapData',
                        name: 'swapData',
                        type: 'tuple',
                    },
                ],
                internalType: 'struct TokenInput',
                name: 'input',
                type: 'tuple',
            },
        ],
        name: 'mintSyFromToken',
        outputs: [{ internalType: 'uint256', name: 'netSyOut', type: 'uint256' }],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            {
                components: [
                    { internalType: 'bool', name: 'allowFailure', type: 'bool' },
                    { internalType: 'bytes', name: 'callData', type: 'bytes' },
                ],
                internalType: 'struct IPActionMiscV3.Call3[]',
                name: 'calls',
                type: 'tuple[]',
            },
        ],
        name: 'multicall',
        outputs: [
            {
                components: [
                    { internalType: 'bool', name: 'success', type: 'bool' },
                    { internalType: 'bytes', name: 'returnData', type: 'bytes' },
                ],
                internalType: 'struct IPActionMiscV3.Result[]',
                name: 'res',
                type: 'tuple[]',
            },
        ],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'user', type: 'address' },
            { internalType: 'address[]', name: 'sys', type: 'address[]' },
            { internalType: 'address[]', name: 'yts', type: 'address[]' },
            { internalType: 'address[]', name: 'markets', type: 'address[]' },
        ],
        name: 'redeemDueInterestAndRewards',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'receiver', type: 'address' },
            { internalType: 'address', name: 'YT', type: 'address' },
            { internalType: 'uint256', name: 'netPyIn', type: 'uint256' },
            { internalType: 'uint256', name: 'minSyOut', type: 'uint256' },
        ],
        name: 'redeemPyToSy',
        outputs: [{ internalType: 'uint256', name: 'netSyOut', type: 'uint256' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'receiver', type: 'address' },
            { internalType: 'address', name: 'YT', type: 'address' },
            { internalType: 'uint256', name: 'netPyIn', type: 'uint256' },
            {
                components: [
                    { internalType: 'address', name: 'tokenOut', type: 'address' },
                    { internalType: 'uint256', name: 'minTokenOut', type: 'uint256' },
                    { internalType: 'address', name: 'tokenRedeemSy', type: 'address' },
                    { internalType: 'address', name: 'pendleSwap', type: 'address' },
                    {
                        components: [
                            {
                                internalType: 'enum SwapType',
                                name: 'swapType',
                                type: 'uint8',
                            },
                            { internalType: 'address', name: 'extRouter', type: 'address' },
                            { internalType: 'bytes', name: 'extCalldata', type: 'bytes' },
                            { internalType: 'bool', name: 'needScale', type: 'bool' },
                        ],
                        internalType: 'struct SwapData',
                        name: 'swapData',
                        type: 'tuple',
                    },
                ],
                internalType: 'struct TokenOutput',
                name: 'output',
                type: 'tuple',
            },
        ],
        name: 'redeemPyToToken',
        outputs: [
            { internalType: 'uint256', name: 'netTokenOut', type: 'uint256' },
            { internalType: 'uint256', name: 'netSyInterm', type: 'uint256' },
        ],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'receiver', type: 'address' },
            { internalType: 'address', name: 'SY', type: 'address' },
            { internalType: 'uint256', name: 'netSyIn', type: 'uint256' },
            {
                components: [
                    { internalType: 'address', name: 'tokenOut', type: 'address' },
                    { internalType: 'uint256', name: 'minTokenOut', type: 'uint256' },
                    { internalType: 'address', name: 'tokenRedeemSy', type: 'address' },
                    { internalType: 'address', name: 'pendleSwap', type: 'address' },
                    {
                        components: [
                            {
                                internalType: 'enum SwapType',
                                name: 'swapType',
                                type: 'uint8',
                            },
                            { internalType: 'address', name: 'extRouter', type: 'address' },
                            { internalType: 'bytes', name: 'extCalldata', type: 'bytes' },
                            { internalType: 'bool', name: 'needScale', type: 'bool' },
                        ],
                        internalType: 'struct SwapData',
                        name: 'swapData',
                        type: 'tuple',
                    },
                ],
                internalType: 'struct TokenOutput',
                name: 'output',
                type: 'tuple',
            },
        ],
        name: 'redeemSyToToken',
        outputs: [
            { internalType: 'uint256', name: 'netTokenOut', type: 'uint256' },
        ],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'target', type: 'address' },
            { internalType: 'bytes', name: 'data', type: 'bytes' },
        ],
        name: 'simulate',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'receiver', type: 'address' },
            { internalType: 'uint256', name: 'minTokenOut', type: 'uint256' },
            {
                components: [
                    { internalType: 'address', name: 'tokenIn', type: 'address' },
                    { internalType: 'uint256', name: 'netTokenIn', type: 'uint256' },
                    { internalType: 'address', name: 'tokenMintSy', type: 'address' },
                    { internalType: 'address', name: 'pendleSwap', type: 'address' },
                    {
                        components: [
                            {
                                internalType: 'enum SwapType',
                                name: 'swapType',
                                type: 'uint8',
                            },
                            { internalType: 'address', name: 'extRouter', type: 'address' },
                            { internalType: 'bytes', name: 'extCalldata', type: 'bytes' },
                            { internalType: 'bool', name: 'needScale', type: 'bool' },
                        ],
                        internalType: 'struct SwapData',
                        name: 'swapData',
                        type: 'tuple',
                    },
                ],
                internalType: 'struct TokenInput',
                name: 'inp',
                type: 'tuple',
            },
        ],
        name: 'swapTokenToToken',
        outputs: [
            { internalType: 'uint256', name: 'netTokenOut', type: 'uint256' },
        ],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'receiver', type: 'address' },
            { internalType: 'address', name: 'SY', type: 'address' },
            {
                components: [
                    { internalType: 'address', name: 'tokenIn', type: 'address' },
                    { internalType: 'uint256', name: 'netTokenIn', type: 'uint256' },
                    { internalType: 'address', name: 'tokenMintSy', type: 'address' },
                    { internalType: 'address', name: 'pendleSwap', type: 'address' },
                    {
                        components: [
                            {
                                internalType: 'enum SwapType',
                                name: 'swapType',
                                type: 'uint8',
                            },
                            { internalType: 'address', name: 'extRouter', type: 'address' },
                            { internalType: 'bytes', name: 'extCalldata', type: 'bytes' },
                            { internalType: 'bool', name: 'needScale', type: 'bool' },
                        ],
                        internalType: 'struct SwapData',
                        name: 'swapData',
                        type: 'tuple',
                    },
                ],
                internalType: 'struct TokenInput',
                name: 'input',
                type: 'tuple',
            },
            { internalType: 'address', name: 'tokenRedeemSy', type: 'address' },
            { internalType: 'uint256', name: 'minTokenOut', type: 'uint256' },
        ],
        name: 'swapTokenToTokenViaSy',
        outputs: [
            { internalType: 'uint256', name: 'netTokenOut', type: 'uint256' },
            { internalType: 'uint256', name: 'netSyInterm', type: 'uint256' },
        ],
        stateMutability: 'payable',
        type: 'function',
    },
];

export default PendleYieldTokenAbi;